version: "2"

services:

  certstore:
    build: .
    image: blockcerts/cert-store:latest
    env_file:
      - ./cert-store-local.env
    command: python -u /cert-store/run.py
    ports:
      - "5003:5003"
